### GET
GET http://localhost:3000/api/health

### Login 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username" : "will@gmail.com",
    "password" : "password123"
}

### ADD MESSAGE 
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3NjcxNDQyMSwiZXhwIjoxNzc2ODAwODIxfQ.dddu_jVJIyXGRgz181hBYHZ6h0ICB1s6ReSgw0NE65c

{
    "post_title": "Testing",
    "post": "Test post to make sure routing and display works"
}

###ADD COMMENT TO POST
POST http://localhost:3000/api/posts/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3NjcxNjUzMCwiZXhwIjoxNzc2ODAyOTMwfQ.WUDjWnNnm9ZmI9wXdyhYK_Y4E9jq-2yon1-6onj-6Bw


{
  "user_id": 1,
  "comment": "Testing comment from REST client"
}

###GET ALL POSTS
GET http://localhost:3000/api/posts

### GET COMMENTS ON A POST
GET http://localhost:3000/api/posts/1/comments